.PHONY: all clean

all:
	@$(MAKE) -C myFileUtils
	@$(MAKE) -C myTextPanel
	@$(MAKE) -C myUiUtils
	@$(MAKE) -C myPanel
	@$(MAKE) -C cmd
	
clean:
	@$(MAKE) -C myFileUtils clean
	@$(MAKE) -C myTextPanel clean
	@$(MAKE) -C myUiUtils clean
	@$(MAKE) -C myPanel clean
	@$(MAKE) -C cmd clean